version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bilet_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=super-secret-key-prod
    volumes:
      - backend_data:/app/prisma

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bilet_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:5000/api
    depends_on:
      - backend

volumes:
  backend_data:
